# random pool of answers
answers_pool = [
    "Absolutely!",
    "Stop doubting yourself.",
    "Put your mind to it.",
    "Let go of your worries.",
    "Look forward to it!",
    "Of course.",
    "Maybe not right now, but in the nearby future.",
    "Take a break and come back to it.",
    "Less doubting, more trusting.",
    "No way!",
    "Not in a million years!",
    "What will be, will be.",
    "Go for it!",
    "Just do it!",
    "Not this time, try again!",
    "Just relax, and the best outcome will come to you.",
    "Ask again tomorrow.",
    "Very good idea!",
    "Anything is possible if you try hard enough.",
    "That is impossible, sorry!",
    "Maybe? Very little chance though.",
    "You already have the answer in your heart.",
    "Watch your back.",
    "As you wish.",
    "You are the master of your life.",
    "Seize the day."
]